ClerkFoodhub/apps/cart/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# router.register(r'providers', views.ProviderViewSet)
router.register(r'all_add-order_by_department', views.OrdersUserViewSet)
router.register(r'all-foods', views.ProvidersViewSet)
# router.register(r'departament', views.DepartamentOrdersViewSet)


app_name = 'cart'

urlpatterns = [
    path('', login_required(views.DashBoardOrders.as_view()), name='main'),
    path('ct/', login_required(views.FoodAllView.as_view()),  name='cart'),
    path('spliwise/', login_required(views.Splitwise), name='spliwise'),
    path('hystory/', login_required(views.MyOrderHystory), name='history'),
    path('buy/', login_required(views.BuyOrderInCatering), name='buycart'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    # path('cart/', login_required(ReadyToOrdered.as_view()), name='cart')
]

ClerkFoodhub/apps/catering/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
# from .views import FoodAllView, ReadyToOrdered


urlpatterns = [
    # path('', login_required(FoodAllView.as_view()), name='main'),
    # path('cart/', login_required(ReadyToOrdered.as_view()), name='cart')
]

ClerkFoodhub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='index.html'), name="home"),
    path('admin/', admin.site.urls),
    # path('catering/', include('catering.urls')),
    path('', include('cart.urls'), name='orders'),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClerkFoodhub/apps/catering/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from site_settings.models import District
# from clients.models import Worker



# --- ------------------ It`s model of providers food to collect food by providers
class Provider(models.Model):
    """
        "title", "link", "id_sort", "date_add", "min_order", "district",
    """
    title = models.CharField('Назва кейтерінгу', max_length=200)
    link = models.URLField('Посилання')
    id_sort = models.PositiveSmallIntegerField('Сортування', default=0)
    date_add = models.DateField(auto_now_add=True)
    min_order = models.PositiveSmallIntegerField('Мінімальне замовлення', default=0)
    district = models.ManyToManyField(District, verbose_name='Обслуговування', blank=True)

    class Meta:
        ordering = ['id_sort']
        verbose_name = 'Кейтерінг'
        verbose_name_plural = '1. Перелік Кейтерінгів'

    def __str__(self):
        return f"{self.title}"


# --- ------------------ It`s model of category food by providers
# --- provider, title, identic, link, id_sort, (date_add)
class CategoryFood(models.Model):
    """
    "provider", "title", "identic", "link", "id_sort", "date_add"
    """

    provider = models.ForeignKey(Provider, verbose_name='Кейтерінг', related_name='categorysfoods', on_delete=models.DO_NOTHING )
    title = models.CharField('Категорія страви', max_length=200)
    identic = models.CharField('ID категорії', max_length=300, null=True, blank=True)
    link = models.URLField('Посилання  категорії', null=True, blank=True)
    id_sort = models.PositiveSmallIntegerField('Сортування', default=0)
    date_add = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['id_sort']
        verbose_name = 'Категорія страв'
        verbose_name_plural = '2. Категорії страв'

    def __str__(self):
        return f"{self.title}"



class Food(models.Model):
    """
    It`s model of food by category
    "category", "title", "description", "price", "buy_link", "image", "link", "id_sort", "is_active", "date_add", "last_update"

    """
    ##TODO  Get from caterig waight of food
    category = models.ForeignKey(CategoryFood, on_delete=models.DO_NOTHING, related_name='foods', verbose_name='Категорія страви')
    title = models.CharField('Страва', max_length=200)
    description = models.TextField('Інгрідієнти', null=True, blank=True)
    weight = models.CharField('Вага', max_length=10, null=True, blank=True, default=0)
    price = models.DecimalField('Ціна', max_digits=6, decimal_places=2)
    buy_link = models.CharField('Посилання на додавання\nУ кошик', max_length=300, null=True, blank=True)
    image = models.CharField('Світлина', max_length=300, null=True, blank=True)
    link = models.CharField('Посилання на сторінку товара', max_length=300, null=True, blank=True)
    id_sort = models.PositiveSmallIntegerField('Сортування', default=0)
    is_active = models.BooleanField('Увімк / Вимк', default=True, help_text='Когда товар неактивен его нельзя заказать. Значит снят с производства.')
    date_add = models.DateField('Дата додавання', auto_now_add=True)
    last_update = models.DateField('Дата оновлення', auto_now=True)

    def food_image_tag(self):
        return mark_safe(f'<img src="{self.image}" width="50" />')

    food_image_tag.short_description = 'Фото'

    class Meta:
        ordering = ['id_sort', 'title']
        verbose_name = 'Страва'
        verbose_name_plural = '3. Страви'

    def __str__(self):
        return f"{self.title}"

ClerkFoodhub/apps/cart/forms.py
from django import forms
import datetime
from .models import Orders

username = str(datetime.datetime.now().timestamp())


class OrdersForm(forms.ModelForm):

    class Meta:
        model = Orders
        fields = '__all__'
        # widgets = {
        #     'userName': forms.TextInput(attrs= {'value': username, 'type': "text", 'readonly':'readonly',}),
        # }

ClerkFoodhub/apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'password')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            'username', 'departament',
            'first_name', 'last_name',
            'email', 'phone',
            'ordering',
            'last_login', 'date_joined',
            'is_active', 'is_staff', 'is_superuser',
            'user_permissions', 'groups'
        )

ClerkFoodhub/apps/cart/views.py
import datetime, locale, sys, copy
from typing import Dict, Any
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from rest_framework import generics
from rest_framework import permissions
from django.contrib.auth.models import User

from django.http import Http404
from django.utils.translation import gettext as _
from .forms import OrdersForm
from django.shortcuts import redirect
from django.db.models import Prefetch
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from cart.serializers import ProvidersSerializer, FoodSerializer, CategoryFoodSerializer, OrdersUserSerializer
from catering.models import Provider, CategoryFood, Food
from users.models import Departament, CustomUser
from cart.models import Orders


# -------------------------- API views-----------------
class FoodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Food.objects.filter(is_active=1)
    serializer_class = FoodSerializer


class CategoryFoodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = CategoryFood.objects.all().prefetch_related(
        Prefetch('foods', queryset=Food.objects.filter(is_active=1)))
    serializer_class = CategoryFoodSerializer


class ProvidersViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    raw_queryset = Provider.objects.all().prefetch_related(
        Prefetch('categorysfoods', queryset=CategoryFood.objects.all().prefetch_related(
            Prefetch('foods', queryset=Food.objects.filter(is_active=1))
        )))

    queryset = raw_queryset
    serializer_class = ProvidersSerializer
    # permission_classes = [permissions.IsAuthenticated]


class OrdersUserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Orders.objects.all()
    serializer_class = OrdersUserSerializer

    def get_queryset(self):
        return Orders.objects.filter(user__departament=self.request.user.departament.id)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


# ------------------------- local views ---------------

class FoodAllView(ListView):
    model = Provider
    template_name = 'catering/manu.html'
    context_object_name = 'providers'
    queryset = Provider.objects.all().prefetch_related(
        Prefetch('categorysfoods', queryset=CategoryFood.objects.all().prefetch_related(
            Prefetch('foods', queryset=Food.objects.filter(is_active=1))
        ))
    )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        order_day = self.request.GET.get('order_day')
        if not order_day:
            order_day = (datetime.datetime.now() + datetime.timedelta(days=1)).strftime('%d-%m-%Y')
        context['order_day'] = order_day
        order_for_day = datetime.datetime.strptime(order_day, '%d-%m-%Y')
        context['ordered'] = Orders.objects.filter(order_for_day=order_for_day, user=self.request.user.id)
        return context

    def post(self, request, *args, **kwargs):
        form = request.POST
        order_for_day = datetime.datetime.strptime(form['order_day'], '%d-%m-%Y')
        user_raw = request.user.username
        user = CustomUser.objects.get(username=user_raw)
        for name, orders in form.items():
            if name == 'csrfmiddlewaretoken' or name == 'order_day':
                continue
            else:
                dish = Food.objects.get(id=name)
                try:
                    allredy_ordered = Orders.objects.get(user=user, food=dish, order_for_day=order_for_day)
                except:
                    allredy_ordered = None

                if allredy_ordered:
                    if int(orders[0]) == 0:
                        allredy_ordered.delete()
                    elif allredy_ordered.quantity != int(orders[0]):
                        allredy_ordered.quantity = orders[0]
                        allredy_ordered.save()
                elif int(orders[0]) == 0:
                    continue
                else:
                    Orders.objects.create(
                        data_add=datetime.datetime.now(),
                        user=user,
                        catering=dish.category.provider,
                        food=dish,
                        quantity=orders[0],
                        order_for_day=order_for_day)
        print(user, order_for_day, )
        return redirect('/')


class DashBoardOrders(ListView):
    model = Orders
    queryset = Orders.objects.all()  # .filter(order_for_day__gte=datetime.datetime.today() + datetime.timedelta(days=1))
    context_object_name = 'dashboard_all'
    template_name = 'cart/orders_list.html'

    def sorting_by_day(self):
        if sys.platform == 'win32':
            locale.setlocale(locale.LC_ALL, 'ukr_ukr')
        else:
            locale.setlocale(locale.LC_ALL, 'uk_UA.UTF-8')
        new_list: dict[int, Any] = dict()
        for d in range(1, 8, 1):
            the_day = (datetime.datetime.today() + datetime.timedelta(days=d))
            if the_day.isoweekday() in range(1, 6):
                new_list[datetime.datetime.strftime(the_day, '%A')] = {
                    "orders": Orders.objects.filter(order_for_day=the_day, user=self.request.user),
                    "order_date": the_day,
                }
        return new_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dashboard'] = self.sorting_by_day()
        return context


def _get_uaser_set(all_order):
    userset = {}
    for i in all_order:
        if i.user.departament not in userset:
            userset[i.user.departament] = [i.user, ]
        elif i.user not in userset[i.user.departament]:
            userset[i.user.departament].append(i.user)
    print(userset)
    return userset


def _colapse_order_by_user(all_orders):
    clients = _get_uaser_set(all_orders)
    orders = {}
    for dep, client_list in clients.items():
        orders[dep] = {}
        for client in client_list:
            client_order_sum = 0
            client_order_id = []
            client_order = all_orders.filter(user=client)
            order_provider = {}
            for i in client_order:
                this_provider = i.food.category.provider
                if this_provider not in order_provider:
                    # client_order_id.append(i.id)
                    # client_order_sum += (i.food.price * i.quantity)
                    order_provider[this_provider] = dict(user=client, order_sum=(i.food.price * i.quantity),
                                                         order_id=[i.id, ])
                else:
                    order_provider[this_provider]['order_id'].append(i.id)
                    order_provider[this_provider]['order_sum'] += (i.food.price * i.quantity)
            orders[dep][client] = order_provider
    return orders


# def _get_my_catering

def BuyOrderInCatering(request):
    """
    :request: страница заказа в кейтеренге
    :return: Вывод всех пользователе компании сгрупированных по отделам, (пользователей, сумма заказа, ID заказов).

    """
    order_day = request.GET.get('order_day')
    if not order_day:
        order_day = (datetime.datetime.now() + datetime.timedelta(days=1))
    print('orderDay={}, request.user.departament.company={}'.format(order_day, request.user.departament.company))
    all_ordered_on_day = Orders.objects.filter(order_for_day=order_day,
                                               user__departament__company=request.user.departament.company, payer=None)
    print('all_oreder', all_ordered_on_day)
    all_department = Departament.objects.filter(company=request.user.departament.company)
    my_order = _colapse_order_by_user(all_ordered_on_day.filter(user=request.user, payer=None))
    orders_by_user = _colapse_order_by_user(all_ordered_on_day.exclude(user=request.user))
    # my_cattering = Provider.objects.get()

    if request.POST:
        form_orders = copy.copy(request.POST)
        form_orders.pop('csrfmiddlewaretoken')
        for i in form_orders:
            orders_ids = i.replace('[', '').replace(']', '').split(',')
            for j in orders_ids:
                order = Orders.objects.get(id=j)
                order.payer = request.user
                order.save()
        print('ppp', form_orders)
        return redirect('/')
    return render(request, 'cart/catering_cart.html', {
        'payed_orders': all_ordered_on_day,
        'my_order': my_order,
        'orders_by_user': orders_by_user
    })


def MyOrderHystory(request):
    all_my_order_nosorted = Orders.objects.filter(user=request.user,
                                                  order_for_day__lte=datetime.datetime.now()).order_by('order_for_day')
    all_my_order = dict()
    for i in all_my_order_nosorted:
        day = str(i.order_for_day)
        if day in all_my_order:
            all_my_order[day].append(i)
        else:
            all_my_order[day] = [i, ]

    return render(request, 'audit/hystory.html', {'all_my_order': all_my_order, })


def Splitwise(request):
    """
    Return the dict:
    {user_login:{
        "user": object_user
        "payments": Он заплатил за меня.
        "debits": Я заплатил за него, он должен мне
        "balance":  debits - payments
        }
    }

    :param request:
    :return:
    """
    all_user_orders = dict()
    client = request.user

    me_payed_orders = Orders.objects.filter(payer=client).exclude(user=client).exclude(payer=None)
    # все заказы которые я оплатил
    for i in me_payed_orders:
        if i.user not in all_user_orders:
            print('create dict', i.user)

ClerkFoodhub/apps/site_settings/views.py
from django.shortcuts import render

# Create your views here.

ClerkFoodhub/templates/catering/main.html
{% extends "base.html" %}
{% load catering_tags %}



{% block title %}{% endblock %}
{% block header %}
<script>
    $(function() {
        let goods = {}
        let raw_item
        let split_data
        let id
        let date
        let item
        $(document).on('click touchstart', 'input[type="checkbox"]', function(){
            if ($(this).prop("checked") == true) {
                let item_row= $(this).parent("div").parent("div").parent("div").parent("div")
                let item_name_raw = item_row.find('h4').text()
                let item_price = item_name_raw.match('\\d+,\\d+')[0].replace(',','.')
                raw_item = $(this).attr("name")
                split_data = raw_item.match(/^(\d+)(\W+)(\d.+)/)
                id = split_data[1]
                date =split_data[3]
                item = split_data[2].replace(/ - /g, '')
                if (goods[date]){
                    goods[date].push({name:item, price:item_price, id:id, fulldata:raw_item})
                 }else{
                    goods[date] = [{name:item, price:item_price, id:id, fulldata:raw_item}]
                 }
            }else{
                if ($(this).prop("checked") == false) {
                    let raw_itemd = $(this).attr("name")
                    let loking_item = raw_itemd.toString()
                    $(`input[name="${loking_item}"]`).prop("checked", false)
                    let num_item = goods[date].indexOf(item)
                    goods[date].splice(num_item, 1)
                    if(!goods[date].length){
                        delete goods[date]
                    }
                 }
            }
            let gd = ''
            let all_summ = 0
            for(let i in goods){
                let day_sum = 0
                let day_order = ''
                for(let j in goods[i]){
                    day_sum += Number(goods[i][j].price)
                    day_order += '<input class="chk-food" type="checkbox" name="'+goods[i][j].fulldata+'" value="'+ goods[i][j].price +'" checked>  ' + goods[i][j].name + ' ' + goods[i][j].price + ' грн<br>'
                }
                gd += "<h6 class='mt-2 p-1 bg-light border-top'>" + i + " за день <span id='sum-by-day'>"+day_sum+"</span> грн</h6>"
                gd += day_order
                all_summ += day_sum
            }
            $("#cart-goods").html(gd)
            $("#all_summ").html(all_summ)
        })
    });
</script>
{% endblock %}
{% block content %}
    <div style="height: 60px;">&nbsp;</div>
    <div class="row w-100">
    <div class="col-1">&nbsp;</div>
    <div class="col mb-4">
        <form>
            <div class="accordion" id="accordionFood">
                {% for food in foods %}
                    {% if food.food_set.all %}
                        <div class="card">
                            <button class="btn btn-link text-left" type="button" data-toggle="collapse" data-target="#collapse_{{ food.id }}" aria-expanded="false" aria-controls="collapse_{{ food.id }}">
                                <div class="card-header" id="{{ food.identic }}">
                                    <h2 class="mb-0">
                                        {{ food }}
                                    </h2>
                                </div>
                            </button>
                            <div id="collapse_{{ food.id }}" class="collapse" aria-labelledby="{{ food.identic }}" data-parent="#accordionFood">
                                <div class="card-body">
                                    {% for foo in food.food_set.all %}
                                        <div class="row border-bottom my-2">
                                            <div class="col-sm-2 border-right"> <img src="{{ foo.image }}" width="100px"></div>
                                            <div class="col-sm-6 border-right"><h4><a href="https://food.imperialcatering.com.ua{{ foo.link }}" target="_blank"> {{ foo.title }}</a> - {{ foo.price }} грн</h4><sub>{{ foo.description }}</sub></div>
                                            <div class="col">
                                                <div class="row">
                                                    <div class="col-sm">{{ 0|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 0|nextdays }}" disabled="disabled"></div>
                                                    <div class="col-sm">{{ 1|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 1|nextdays }}"></div>
                                                    <div class="col-sm">{{ 2|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 2|nextdays }}"></div>
                                                    <div class="col-sm">{{ 3|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 3|nextdays }}"></div>
                                                    <div class="col-sm">{{ 4|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 4|nextdays }}"></div>
                                                    <div class="col-sm">{{ 5|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 5|nextdays }}"></div>
                                                    <div class="col-sm">{{ 6|wekdays }}<br /><input class="chk-food" type="checkbox" name="{{ foo.id }} - {{ foo.title }} - {{ 6|nextdays }}"></div>
                                                    {#                                            <div class="col-sm-2">{% now "D" %}<br /><input type="checkbox" name="{{ foo.title }} - Mon"></div>#}
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                    {% endif %}
                {% endfor %}
            </div>
        </form>
    </div>
    <div class="col-2">
        <form method="post">
            {% csrf_token %}
            <div id="cart" class="col-2 position-fixed">
                <p class="h4">Корзина -  <span id="all_summ"></span>грн</p>
                <div id="cart-goods" class="overflow-auto" style="max-height: 65vh;"></div>
                <hr />
                <button class="btn btn-success"><span class="btn_form_text">Замовити</span></button>
            </div>
        </form>
    </div>
{% endblock %}

ClerkFoodhub/templates/catering/order_cart.html
{% extends 'base.html'  %}

{% block content %}
    {% for date, dish in dishes.items %}
        <div>
        <h4>{{ date }}</h4>
            <ul>
            {% for d in dish %}
                <li><img src="{{ d.image }}" width="100px"><a href="https://food.imperialcatering.com.ua/{{ d.link }}" target="_blank"> {{ d }}</a> - {{ d.quantity }} шт -{{ d.price }}</li>
            {% endfor %}
            </ul>
        </div>

        - {{ dish.user }} - {{ dish.payer }}

    {% endfor %}
{% endblock %}

{# ------ TODO ------ #}
{#  link for ordering #}
{#  https://food.imperialcatering.com.ua/index.php?option=com_jshopping&controller=cart&task=add&quantity=5&to=cart&product_id=972&category_id=9  #}