ClerkFoodhub/apps/cart/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# router.register(r'providers', views.ProviderViewSet)
router.register(r'all_add-order_by_department', views.OrdersUserViewSet)
router.register(r'all-foods', views.ProvidersViewSet)
# router.register(r'departament', views.DepartamentOrdersViewSet)


app_name = 'cart'

urlpatterns = [
    path('', login_required(views.DashBoardOrders.as_view()), name='main'),
    path('ct/', login_required(views.FoodAllView.as_view()),  name='cart'),
    path('spliwise/', login_required(views.Splitwise), name='spliwise'),
    path('hystory/', login_required(views.MyOrderHystory), name='history'),
    path('buy/', login_required(views.BuyOrderInCatering), name='buycart'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    # path('cart/', login_required(ReadyToOrdered.as_view()), name='cart')
]

ClerkFoodhub/apps/catering/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
# from .views import FoodAllView, ReadyToOrdered


urlpatterns = [
    # path('', login_required(FoodAllView.as_view()), name='main'),
    # path('cart/', login_required(ReadyToOrdered.as_view()), name='cart')
]

ClerkFoodhub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='index.html'), name="home"),
    path('admin/', admin.site.urls),
    # path('catering/', include('catering.urls')),
    path('', include('cart.urls'), name='orders'),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClerkFoodhub/apps/site_settings/models.py
from django.db import models


class City(models.Model):
    title = models.CharField('Назва міста', max_length=50)
    ordering = models.PositiveSmallIntegerField('Сортування', default=0)
    date_add = models.DateTimeField('Дата додавання', auto_now_add=True)

    class Meta:
        ordering = ['ordering']
        verbose_name = 'Місто'
        verbose_name_plural = '1. Міста'

    def __str__(self):
        return f"{self.title}"

class Region(models.Model):
    city = models.ForeignKey(City, verbose_name='Місто', on_delete=models.DO_NOTHING)
    title = models.CharField('Частина міста', max_length=50)
    ordering = models.PositiveSmallIntegerField('Сортування', default=0)
    date_add = models.DateTimeField('Дата додавання', auto_now_add=True)

    class Meta:
        ordering = ['ordering']
        verbose_name = 'Частину міста'
        verbose_name_plural = '2. Частини міста'

    def __str__(self):
        return f"{self.title}"


class District(models.Model):
    region = models.ForeignKey(Region, verbose_name='Місто', on_delete=models.DO_NOTHING)
    title = models.CharField('Назва району', max_length=50)
    ordering = models.PositiveSmallIntegerField('Сортування', default=0)
    date_add = models.DateTimeField('Дата додавання', auto_now_add=True)

    class Meta:
        ordering = ['ordering']
        verbose_name = 'Район'
        verbose_name_plural = '3. Райони'

    def __str__(self):
        return f"{self.title}"

ClerkFoodhub/apps/cart/forms.py
from django import forms
import datetime
from .models import Orders

username = str(datetime.datetime.now().timestamp())


class OrdersForm(forms.ModelForm):

    class Meta:
        model = Orders
        fields = '__all__'
        # widgets = {
        #     'userName': forms.TextInput(attrs= {'value': username, 'type': "text", 'readonly':'readonly',}),
        # }

ClerkFoodhub/apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'password')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            'username', 'departament',
            'first_name', 'last_name',
            'email', 'phone',
            'ordering',
            'last_login', 'date_joined',
            'is_active', 'is_staff', 'is_superuser',
            'user_permissions', 'groups'
        )

ClerkFoodhub/apps/cart/views.py
import datetime, locale, sys, copy
from typing import Dict, Any
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from rest_framework import generics
from rest_framework import permissions
from django.contrib.auth.models import User

from django.http import Http404
from django.utils.translation import gettext as _
from .forms import OrdersForm
from django.shortcuts import redirect
from django.db.models import Prefetch
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from cart.serializers import ProvidersSerializer, FoodSerializer, CategoryFoodSerializer, OrdersUserSerializer
from catering.models import Provider, CategoryFood, Food
from users.models import Departament, CustomUser
from cart.models import Orders


# -------------------------- API views-----------------
class FoodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Food.objects.filter(is_active=1)
    serializer_class = FoodSerializer


class CategoryFoodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = CategoryFood.objects.all().prefetch_related(
        Prefetch('foods', queryset=Food.objects.filter(is_active=1)))
    serializer_class = CategoryFoodSerializer


class ProvidersViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    raw_queryset = Provider.objects.all().prefetch_related(
        Prefetch('categorysfoods', queryset=CategoryFood.objects.all().prefetch_related(
            Prefetch('foods', queryset=Food.objects.filter(is_active=1))
        )))

    queryset = raw_queryset
    serializer_class = ProvidersSerializer
    # permission_classes = [permissions.IsAuthenticated]


class OrdersUserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Orders.objects.all()
    serializer_class = OrdersUserSerializer

    def get_queryset(self):
        return Orders.objects.filter(user__departament=self.request.user.departament.id)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


# ------------------------- local views ---------------

class FoodAllView(ListView):
    model = Provider
    template_name = 'catering/manu.html'
    context_object_name = 'providers'
    queryset = Provider.objects.all().prefetch_related(
        Prefetch('categorysfoods', queryset=CategoryFood.objects.all().prefetch_related(
            Prefetch('foods', queryset=Food.objects.filter(is_active=1))
        ))
    )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        order_day = self.request.GET.get('order_day')
        if not order_day:
            order_day = (datetime.datetime.now() + datetime.timedelta(days=1)).strftime('%d-%m-%Y')
        context['order_day'] = order_day
        order_for_day = datetime.datetime.strptime(order_day, '%d-%m-%Y')
        context['ordered'] = Orders.objects.filter(order_for_day=order_for_day, user=self.request.user.id)
        return context

    def post(self, request, *args, **kwargs):
        form = request.POST
        order_for_day = datetime.datetime.strptime(form['order_day'], '%d-%m-%Y')
        user_raw = request.user.username
        user = CustomUser.objects.get(username=user_raw)
        for name, orders in form.items():
            if name == 'csrfmiddlewaretoken' or name == 'order_day':
                continue
            else:
                dish = Food.objects.get(id=name)
                try:
                    allredy_ordered = Orders.objects.get(user=user, food=dish, order_for_day=order_for_day)
                except:
                    allredy_ordered = None

                if allredy_ordered:
                    if int(orders[0]) == 0:
                        allredy_ordered.delete()
                    elif allredy_ordered.quantity != int(orders[0]):
                        allredy_ordered.quantity = orders[0]
                        allredy_ordered.save()
                elif int(orders[0]) == 0:
                    continue
                else:
                    Orders.objects.create(
                        data_add=datetime.datetime.now(),
                        user=user,
                        catering=dish.category.provider,
                        food=dish,
                        quantity=orders[0],
                        order_for_day=order_for_day)
        print(user, order_for_day, )
        return redirect('/')


class DashBoardOrders(ListView):
    model = Orders
    queryset = Orders.objects.all()  # .filter(order_for_day__gte=datetime.datetime.today() + datetime.timedelta(days=1))
    context_object_name = 'dashboard_all'
    template_name = 'cart/orders_list.html'

    def sorting_by_day(self):
        if sys.platform == 'win32':
            locale.setlocale(locale.LC_ALL, 'ukr_ukr')
        else:
            locale.setlocale(locale.LC_ALL, 'uk_UA.UTF-8')
        new_list: dict[int, Any] = dict()
        for d in range(1, 8, 1):
            the_day = (datetime.datetime.today() + datetime.timedelta(days=d))
            if the_day.isoweekday() in range(1, 6):
                new_list[datetime.datetime.strftime(the_day, '%A')] = {
                    "orders": Orders.objects.filter(order_for_day=the_day, user=self.request.user),
                    "order_date": the_day,
                }
        return new_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dashboard'] = self.sorting_by_day()
        return context


def _get_uaser_set(all_order):
    userset = {}
    for i in all_order:
        if i.user.departament not in userset:
            userset[i.user.departament] = [i.user, ]
        elif i.user not in userset[i.user.departament]:
            userset[i.user.departament].append(i.user)
    print(userset)
    return userset


def _colapse_order_by_user(all_orders):
    clients = _get_uaser_set(all_orders)
    orders = {}
    for dep, client_list in clients.items():
        orders[dep] = {}
        for client in client_list:
            client_order_sum = 0
            client_order_id = []
            client_order = all_orders.filter(user=client)
            order_provider = {}
            for i in client_order:
                this_provider = i.food.category.provider
                if this_provider not in order_provider:
                    # client_order_id.append(i.id)
                    # client_order_sum += (i.food.price * i.quantity)
                    order_provider[this_provider] = dict(user=client, order_sum=(i.food.price * i.quantity),
                                                         order_id=[i.id, ])
                else:
                    order_provider[this_provider]['order_id'].append(i.id)
                    order_provider[this_provider]['order_sum'] += (i.food.price * i.quantity)
            orders[dep][client] = order_provider
    return orders


# def _get_my_catering

def BuyOrderInCatering(request):
    """
    :request: страница заказа в кейтеренге
    :return: Вывод всех пользователе компании сгрупированных по отделам, (пользователей, сумма заказа, ID заказов).

    """
    order_day = request.GET.get('order_day')
    if not order_day:
        order_day = (datetime.datetime.now() + datetime.timedelta(days=1))
    print('orderDay={}, request.user.departament.company={}'.format(order_day, request.user.departament.company))
    all_ordered_on_day = Orders.objects.filter(order_for_day=order_day,
                                               user__departament__company=request.user.departament.company, payer=None)
    print('all_oreder', all_ordered_on_day)
    all_department = Departament.objects.filter(company=request.user.departament.company)
    my_order = _colapse_order_by_user(all_ordered_on_day.filter(user=request.user, payer=None))
    orders_by_user = _colapse_order_by_user(all_ordered_on_day.exclude(user=request.user))
    # my_cattering = Provider.objects.get()

    if request.POST:
        form_orders = copy.copy(request.POST)
        form_orders.pop('csrfmiddlewaretoken')
        for i in form_orders:
            orders_ids = i.replace('[', '').replace(']', '').split(',')
            for j in orders_ids:
                order = Orders.objects.get(id=j)
                order.payer = request.user
                order.save()
        print('ppp', form_orders)
        return redirect('/')
    return render(request, 'cart/catering_cart.html', {
        'payed_orders': all_ordered_on_day,
        'my_order': my_order,
        'orders_by_user': orders_by_user
    })


def MyOrderHystory(request):
    all_my_order_nosorted = Orders.objects.filter(user=request.user,
                                                  order_for_day__lte=datetime.datetime.now()).order_by('order_for_day')
    all_my_order = dict()
    for i in all_my_order_nosorted:
        day = str(i.order_for_day)
        if day in all_my_order:
            all_my_order[day].append(i)
        else:
            all_my_order[day] = [i, ]

    return render(request, 'audit/hystory.html', {'all_my_order': all_my_order, })


def Splitwise(request):
    """
    Return the dict:
    {user_login:{
        "user": object_user
        "payments": Он заплатил за меня.
        "debits": Я заплатил за него, он должен мне
        "balance":  debits - payments
        }
    }

    :param request:
    :return:
    """
    all_user_orders = dict()
    client = request.user

    me_payed_orders = Orders.objects.filter(payer=client).exclude(user=client).exclude(payer=None)
    # все заказы которые я оплатил
    for i in me_payed_orders:
        if i.user not in all_user_orders:
            print('create dict', i.user)

ClerkFoodhub/apps/catering/views.py
import datetime
from typing import Dict, Any

from django.shortcuts import render
from django.db.models import Prefetch
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from catering.models import Provider, CategoryFood, Food


def make_food_set(form):
    order = {}
    for i in form:
        if i != 'csrfmiddlewaretoken':
            # print(f'i - {i}')
            order_dish_date = i.split(' - ')
            order_date = order_dish_date[2]
            order_dish = Food.objects.get(id=order_dish_date[0])
            try:
                order_key = order[order_date]
                order_key.append(order_dish)
                order[order_date] = order_key
            except:
                order[order_date] = [order_dish,]
    return order


# class FoodAllView(ListView):
#     model = CategoryFood
#     template_name = 'catering/main.html'
#     context_object_name = 'foods'
#     raw_queryset = CategoryFood.objects.all().prefetch_related(Prefetch('food_set', queryset=Food.objects.filter(is_active=1)))
#     queryset = raw_queryset
#
#     def post(self, request, *args, **kwargs):
#         form = request.POST
#         user_raw = request.user.username
#         user = Worker.objects.get(username=user_raw)
#         order_list = make_food_set(form)
#         for key, order in order_list.items():
#             order_date = datetime.datetime.strptime(key, '%d/%m/%Y %H:%M')
#             new_order = Orders.objects.create(user=user, quantity=1, order_for_day=order_date)
#             for dish in order:
#                 new_order.food.add(dish)
#         return self.get(request, *args, **kwargs)



class ReadyToOrdered(ListView):
    def sorting_by_day(orders):
        new_list: dict[str, Any] = dict()
        for ord in orders:
            try:
                foodlist = new_list[str(ord.order_for_day)]
                for i in ord.food.all():
                    if i in foodlist:
                        foodlist[i]['quantity'] += 1
                    else:
                        foodlist[i] = i.__dict__
                        foodlist[i]['quantity'] = 1
            except:
                foodlist = dict()
                for i in ord.food.all():
                    foodlist[i] = i.__dict__
                    foodlist[i]['quantity'] = 1
                new_list[str(ord.order_for_day)] = foodlist
        return new_list
    model = Orders
    future_orders = Orders.objects.filter(order_for_day__gte=datetime.datetime.today())
    queryset = sorting_by_day(future_orders)
    template_name = 'catering/order_cart.html'
    context_object_name = 'dishes'

ClerkFoodhub/apps/site_settings/views.py
from django.shortcuts import render

# Create your views here.

ClerkFoodhub/templates/cart/catering_cart.html
{% extends "base.html" %}
{% load catering_tags %}
{% block title %}SplitWise{% endblock %}
{% block header %}
    <script>
        function get_sums(){
            let prov_order = {'all':0}
            $("input:checked").each(function () {
                let ord = $(this).attr('price_chek')
                let prov = $(this).attr('provider')
                if(prov in prov_order){
                    prov_order[prov] += Number(ord.replace(',', '.'))
                    prov_order['all'] += Number(ord.replace(',', '.'))
                }else{
                    prov_order[prov] = Number(ord.replace(',', '.'))
                    prov_order['all'] += Number(ord.replace(',', '.'))
                }
                console.log(prov_order)
            })
            return prov_order
        }
        function write_data_summ(order_sum){
            let validator_summ = []
            let by_prov_string = ''
            for(key in order_sum){
                if(key=='all'){
                    $('#all_order_sum').text(order_sum[key])
                }else{
                    {###TODO сделать чтоб сумма тянулась из провадера #}
                    if(order_sum[key]<500){
                        by_prov_string += ('<div class="border-left px-2 text-center text-danger providersum">' + key + '<br>' + order_sum[key] + ' грн</div>')
                        validator_summ.push(false)
                    }else {
                        by_prov_string += ('<div class="border-left px-2 text-center text-success providersum">' + key + '<br>' + order_sum[key] + ' грн</div>')
                        validator_summ.push(true)
                    }
                }
            }
            $('#by_providers').html(by_prov_string)
            if(validator_summ.every(elem => elem == true)){
                $('#submit_order').removeAttr('disabled')
            }else{
                $('#submit_order').attr('disabled', 'true')
            }
            console.log(validator_summ.every(elem => elem == true))
        }
        function falidate_sum(){
            validator_summ.every(elem => elem == true)
        }

        $(document).ready(function () {
            write_data_summ(get_sums())
            $("input").click(function () {
                let ord = write_data_summ(get_sums())

            })
        })
    </script>
    <style>
        .dep:nth-child(odd){
            background: rgba(0,0,0,0.1);

        }
        .dep:last-child{
            margin-bottom: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="mx-auto w-50">
        <div class="card-header d-flex justify-content-between">
            <h5 class="text-uppercase ">Сумма замовлення: <span id="all_order_sum"></span></h5>
            <div class="d-flex" id="order_sum">

                <div id="by_providers" class="d-flex"></div>
            </div>
        </div>
    <form method="post">
        {% csrf_token %}
        {% for dep, users in my_order.items %}
            <ul>
            {% for user, providers in users.items %}
                <li class="d-block">
                <div class="w-100">&nbsp; &nbsp;<label>My order</label></div>
                    {% for prov, order in providers.items %}
                        <div class="d-flex justify-content-end">
                            <div class="px-3 ">{{ prov }} </div>
                            <div class="pr-3"><span class="order_sum">{{ order.order_sum }}</span>&nbsp;грн</div>
                            <input type="checkbox" name='{{ order.order_id }}' price_chek="{{ order.order_sum }}" provider="{{ prov }}" checked>
                        </div>
                    {% endfor %}
                </li>
            {% endfor %}
            </ul>
        {% endfor %}


        {% for dep, userset in orders_by_user.items %}
            <div class="dep px-2 py-1">
                <p class="border-bottom text-center mt-1 text-uppercase">{{ dep }}</p>
                <ol>
                    {% for username, providers in userset.items %}
                        <li class="d-flex justify-content-between ">
                            <div class="w-100">{{ forloop.counter }}. &nbsp;<label>{{ username }}</label>
                                {% for provider, user  in providers.items %}
                                    <div class="d-flex justify-content-end">
                                        <div class="px-3">{{ provider }} </div>
                                        <div class="px-3"><span class="order_sum">{{ user.order_sum }}</span>&nbsp;грн
                                        </div>
                                        <input type="checkbox" name="{{ user.order_id }}"
                                               price_chek="{{ user.order_sum }}" provider="{{ provider }}">
                                    </div>
                                {% endfor %}
                            </div>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        {% endfor %}
        <input type="submit" value="Оплатити заказ" class="w-100" id="submit_order">
    </form>
    </div>
{#----------------------------------------------------------------------#}
{#    <div>#}
{#    {% for dep, users in my_order.items %}#}
{#    <div>#}
{#    <h3>{{ dep }}</h3>#}
{#        {% for user, providers in users.items %}#}
{#        <p>{{ user }}#}
{#            <ul>#}
{#            {% for provider, orders in providers.items %}#}
{#            {{ provider }}#}
{#            <li>#}
{#                {{ orders }}#}
{#            </li>#}
{#            {% endfor %}#}
{##}
{#            </ul>#}
{#        </p>#}
{#        {% endfor %}#}
{#    </div>#}
{##}
{#    {% endfor %}#}
{##}
{#    </div>#}
{#    <p>&nbsp;<br></p>#}
{#  --------------------------------------------------------------------------------  #}
{% endblock %}

ClerkFoodhub/templates/cart/orders_list.html
{% extends "base.html" %}
{% load catering_tags %}
{% block title %}Dashboard{% endblock %}
{% block header %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <style>
    .card-header, .hover, .price_footer{
        min-width: 200px;
    }
    h1{
        font-size: 4rem;
        border-bottom: 1px solid #ddd;
        margin-bottom: 40px;
    }
    </style>
    <script>

    function equalize_height(classname){
        let max_height = 0
        $(classname).each(function(){
            if($(this).height() > max_height){
                max_height = $(this).height()
            }
        })
        $(classname).each(function(){
            $(this).height(max_height)
        })
        console.log(classname, '=', max_height+'px')

    }
    $(document).ready(function () {
        let height_validater = ['.card-header', '.card-boady', '.card-footer']
        for(let i=0; i < height_validater.length; i++){
            equalize_height(height_validater[i])
        }
    })
    </script>
{% endblock %}
{% block content %}
    <h1 class="text-center">Мої замовлення</h1>
    <div class="row row-cols-5 justify-content-center mx-5">
        {% for day, orders_list in dashboard.items %}
            <div class="col hover flex-1">
                <div>
                    <div class="d-flex flex-wrap card-header" style="border-bottom: 1px solid gray">
                        <h3 class="text-uppercase"><a
                                href="{% url 'cart:cart' %}?order_day={{ orders_list.order_date|date:"d-m-Y" }}"
                                title="Редагувати замовлення">{{ day }}</a></h3>
                        <sup class="m-2 text-center ml-auto">{{ orders_list.order_date|date:"d-m-Y" }}</sup>
                    </div>
                    <div class="card-boady">
                        {% if orders_list.orders %}
                            <ol>
                                {% for food in orders_list.orders %}
                                    {% if request.user == food.user %}
                                        <li class="{% if food.payer %}text-light bg-info d-flex justify-content-between{% endif %} my-1">
                                            <div>{{ food.food }} {{ food.quantity }}шт</div>
                                            {% if food.payer %}
                                                <span class="material-symbols-outlined my-auto mr-2"
                                                      style="font-size: 14px"
                                                      title="Замовлення в дорозі">local_shipping</span>
                                            {% endif %}
                                            <span hidden class="price">{{ food.food.price }}</span>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ol>

                        {% else %}
                            <h4 class="text-danger text-center"><br>Додай сюди <br>щось смачненьке ;)</h4>
                        {% endif %}
                    </div>
                    <div class="col my-5">
                        <div class="card-footer">
                            {% if orders_list.orders %}
                                <h6>Сума вашого замовлення: &nbsp; {{ orders_list.orders|summ_order }} грн</h6>
                                <a class="btn btn-outline-primary w-100"
                                   href="{% url 'cart:buycart' %}?order_day={{ orders_list.order_date|date:"Y-m-d" }}"
                                   title="Оплатити за {{ day }}">Оплатити</a>
                            {% else %}
                                <div class="text-danger">Безкоштовно</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

ClerkFoodhub/templates/cart/splitwise.html
{% extends "base.html" %}
{% load catering_tags %}
{% block title %}SplitWise{% endblock %}
{% block header %}{% endblock %}
{% block content %}
    <div class="container">
    <table width="100%" cellpadding="5px">
    <tr>
        <th>Користувач</th>
        <th>Он заплатил за меня</th>
        <th>Я заплатил за него</th>
        <th>Баланс</th>
    </tr>
    
{% for login, data in payed_orders.items %}

    <tr class="{% if data.balance < 0  %}text-danger list-group-item-warning{% endif %}">
        <td>{{ data.user }}</td>
        <td>{{ data.payments }}</td>
        <td>{{ data.debit }}</td>
        <td>
            <a title="{% if data.balance > 0  %}
                он мне должен
            {% else %}
                я ему должен
            {% endif %}">
            {{ data.balance }} грн</a>
        </td>

    </tr>

{% endfor %}
</table>
    </div>
{% endblock %}